/**
 * All 48 FIFA World Cup 2026 teams — data for programmatic SEO pages.
 * Used by /world-cup-2026/teams/[slug]/page.tsx
 *
 * apiName: the team name as returned by football-data.org API (used to filter matches)
 */

export interface WCTeamEntry {
  slug: string;           // URL slug: 'argentina', 'france', etc.
  displayName: string;    // Display name
  shortName: string;      // Short name for compact UI
  apiName: string;        // Matches football-data.org homeTeam.name / awayTeam.name
  flag: string;           // Emoji flag
  group: string;          // 'A'–'L' or 'TBD'
  fifaRanking: number;    // Approximate FIFA ranking (June 2025)
  confederation: 'UEFA' | 'CONMEBOL' | 'CONCACAF' | 'CAF' | 'AFC' | 'OFC';
  qualified: boolean;     // true = confirmed qualifier or host
  metaTitle: string;
  metaDesc: string;
  intro: string;          // Short team intro for the page
}

// ---------------------------------------------------------------------------
// Full 48-team roster
// ---------------------------------------------------------------------------

export const WC_ALL_TEAMS: WCTeamEntry[] = [
  // ── CONCACAF (6) ──────────────────────────────────────────────────────────
  {
    slug: 'usa',
    displayName: 'United States',
    shortName: 'USA',
    apiName: 'United States',
    flag: '🇺🇸',
    group: 'A',
    fifaRanking: 13,
    confederation: 'CONCACAF',
    qualified: true,
    metaTitle: 'USA at FIFA World Cup 2026 — Fixtures, Results & Squad | GoalRadar',
    metaDesc: 'USA World Cup 2026 fixtures, results, group standing and squad. Follow the USMNT at the home World Cup — schedule, TV guide and match updates.',
    intro: 'The United States Men\'s National Team co-host the FIFA World Cup 2026 alongside Canada and Mexico. Playing on home soil, the USMNT enter the tournament with high expectations and significant home-crowd advantage across their host city stadiums.',
  },
  {
    slug: 'canada',
    displayName: 'Canada',
    shortName: 'Canada',
    apiName: 'Canada',
    flag: '🇨🇦',
    group: 'B',
    fifaRanking: 47,
    confederation: 'CONCACAF',
    qualified: true,
    metaTitle: 'Canada at FIFA World Cup 2026 — Fixtures, Results & Squad | GoalRadar',
    metaDesc: 'Canada World Cup 2026 fixtures, group standing and squad. Follow Les Rouges at their home World Cup — match schedule and live updates.',
    intro: 'Canada co-host the FIFA World Cup 2026, appearing in just their second-ever World Cup tournament. The Canadians bring a young, fast squad led by stars from the Premier League and MLS, aiming to make history on home soil.',
  },
  {
    slug: 'mexico',
    displayName: 'Mexico',
    shortName: 'Mexico',
    apiName: 'Mexico',
    flag: '🇲🇽',
    group: 'C',
    fifaRanking: 15,
    confederation: 'CONCACAF',
    qualified: true,
    metaTitle: 'Mexico at FIFA World Cup 2026 — Fixtures, Results & Squad | GoalRadar',
    metaDesc: 'Mexico World Cup 2026 fixtures, group standing and squad. El Tri host the opening match at Azteca Stadium — schedule, TV guide and match updates.',
    intro: 'Mexico host the FIFA World Cup opening match at the iconic Azteca Stadium on 11 June 2026. El Tri are one of three co-hosts and bring enormous fan support and decades of World Cup experience to the tournament.',
  },
  {
    slug: 'costa-rica',
    displayName: 'Costa Rica',
    shortName: 'Costa Rica',
    apiName: 'Costa Rica',
    flag: '🇨🇷',
    group: 'D',
    fifaRanking: 49,
    confederation: 'CONCACAF',
    qualified: true,
    metaTitle: 'Costa Rica at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Costa Rica World Cup 2026 fixtures, results and group standing. Los Ticos World Cup schedule and match updates.',
    intro: 'Costa Rica qualified for the FIFA World Cup 2026 through the CONCACAF qualification process. Los Ticos are known for their defensive resilience and tactical discipline, with a history of surprising stronger opponents on the World Cup stage.',
  },
  {
    slug: 'panama',
    displayName: 'Panama',
    shortName: 'Panama',
    apiName: 'Panama',
    flag: '🇵🇦',
    group: 'E',
    fifaRanking: 53,
    confederation: 'CONCACAF',
    qualified: true,
    metaTitle: 'Panama at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Panama World Cup 2026 fixtures, results and group standing. Los Canaleros World Cup schedule and match updates.',
    intro: 'Panama secured their place at the FIFA World Cup 2026, continuing the nation\'s rapid rise in CONCACAF football. Los Canaleros are disciplined and hard to beat, making them a dangerous opponent in the group stage.',
  },
  {
    slug: 'honduras',
    displayName: 'Honduras',
    shortName: 'Honduras',
    apiName: 'Honduras',
    flag: '🇭🇳',
    group: 'F',
    fifaRanking: 68,
    confederation: 'CONCACAF',
    qualified: true,
    metaTitle: 'Honduras at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Honduras World Cup 2026 fixtures, results and group standing. La Bicolor World Cup schedule and match updates.',
    intro: 'Honduras return to the FIFA World Cup stage in 2026 after qualifying through the CONCACAF Octagonal. La Bicolor have a passionate fan base and a tradition of competitive performances in the region\'s qualifying stages.',
  },
  // ── CONMEBOL (6) ──────────────────────────────────────────────────────────
  {
    slug: 'argentina',
    displayName: 'Argentina',
    shortName: 'Argentina',
    apiName: 'Argentina',
    flag: '🇦🇷',
    group: 'G',
    fifaRanking: 1,
    confederation: 'CONMEBOL',
    qualified: true,
    metaTitle: 'Argentina at FIFA World Cup 2026 — Fixtures, Results & Squad | GoalRadar',
    metaDesc: 'Argentina World Cup 2026 fixtures, results, group standing and squad. Follow the defending champions — schedule, TV guide and match updates.',
    intro: 'Argentina arrive at the FIFA World Cup 2026 as the reigning world champions, looking to defend the title they won so dramatically in Qatar 2022. Led by Lionel Messi in what is expected to be his final World Cup, La Albiceleste are among the tournament favourites.',
  },
  {
    slug: 'brazil',
    displayName: 'Brazil',
    shortName: 'Brazil',
    apiName: 'Brazil',
    flag: '🇧🇷',
    group: 'H',
    fifaRanking: 5,
    confederation: 'CONMEBOL',
    qualified: true,
    metaTitle: 'Brazil at FIFA World Cup 2026 — Fixtures, Results & Squad | GoalRadar',
    metaDesc: 'Brazil World Cup 2026 fixtures, results, group standing and squad. Follow the Seleção — schedule, TV guide and match updates.',
    intro: 'Brazil, five-time world champions and the most successful nation in World Cup history, arrive in 2026 desperate to end a 24-year wait for the Hexacampeonato. The Seleção bring world-class talent and the passionate support of the football-mad Brazilian nation.',
  },
  {
    slug: 'colombia',
    displayName: 'Colombia',
    shortName: 'Colombia',
    apiName: 'Colombia',
    flag: '🇨🇴',
    group: 'I',
    fifaRanking: 9,
    confederation: 'CONMEBOL',
    qualified: true,
    metaTitle: 'Colombia at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Colombia World Cup 2026 fixtures, results and group standing. Los Cafeteros World Cup schedule and match updates.',
    intro: 'Colombia qualified for the FIFA World Cup 2026 after a strong CONMEBOL qualification campaign. Los Cafeteros have been resurgent in South American football and enter the tournament as genuine dark-horse contenders.',
  },
  {
    slug: 'uruguay',
    displayName: 'Uruguay',
    shortName: 'Uruguay',
    apiName: 'Uruguay',
    flag: '🇺🇾',
    group: 'J',
    fifaRanking: 14,
    confederation: 'CONMEBOL',
    qualified: true,
    metaTitle: 'Uruguay at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Uruguay World Cup 2026 fixtures, results and group standing. La Celeste World Cup schedule and match updates.',
    intro: 'Uruguay, two-time world champions, are perennial contenders in international football. La Celeste punch above their weight at every World Cup and in 2026 will look to go deep in the tournament once again under their experienced coaching staff.',
  },
  {
    slug: 'ecuador',
    displayName: 'Ecuador',
    shortName: 'Ecuador',
    apiName: 'Ecuador',
    flag: '🇪🇨',
    group: 'K',
    fifaRanking: 44,
    confederation: 'CONMEBOL',
    qualified: true,
    metaTitle: 'Ecuador at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Ecuador World Cup 2026 fixtures, results and group standing. La Tri World Cup schedule and match updates.',
    intro: 'Ecuador secured their World Cup 2026 qualification through another strong CONMEBOL campaign. La Tri have been one of the most consistent South American sides in recent years and bring a high-energy attacking style to the tournament.',
  },
  {
    slug: 'venezuela',
    displayName: 'Venezuela',
    shortName: 'Venezuela',
    apiName: 'Venezuela',
    flag: '🇻🇪',
    group: 'L',
    fifaRanking: 31,
    confederation: 'CONMEBOL',
    qualified: true,
    metaTitle: 'Venezuela at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Venezuela World Cup 2026 fixtures, results and group standing. La Vinotinto World Cup schedule and match updates.',
    intro: 'Venezuela make a historic appearance at the FIFA World Cup 2026, marking a new era for South American football. La Vinotinto\'s qualification represents the breakthrough of a generation of talented players who have developed in European leagues.',
  },
  // ── UEFA (16) ─────────────────────────────────────────────────────────────
  {
    slug: 'france',
    displayName: 'France',
    shortName: 'France',
    apiName: 'France',
    flag: '🇫🇷',
    group: 'A',
    fifaRanking: 2,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'France at FIFA World Cup 2026 — Fixtures, Results & Squad | GoalRadar',
    metaDesc: 'France World Cup 2026 fixtures, results, group standing and squad. Follow Les Bleus — schedule, TV guide and match updates.',
    intro: 'France, the 2018 world champions and 2022 runners-up, are among the strongest favourites for the FIFA World Cup 2026. Les Bleus boast a golden generation of talent and carry the weight of expectation as one of the greatest squads in international football history.',
  },
  {
    slug: 'england',
    displayName: 'England',
    shortName: 'England',
    apiName: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    group: 'B',
    fifaRanking: 4,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'England at FIFA World Cup 2026 — Fixtures, Results & Squad | GoalRadar',
    metaDesc: 'England World Cup 2026 fixtures, results, group standing and squad. Follow the Three Lions — schedule, TV guide and match updates.',
    intro: 'England arrive at the FIFA World Cup 2026 as serious contenders after reaching consecutive tournament finals. The Three Lions carry the hopes of a nation and the talent to finally end 60 years of hurt at a major tournament.',
  },
  {
    slug: 'spain',
    displayName: 'Spain',
    shortName: 'Spain',
    apiName: 'Spain',
    flag: '🇪🇸',
    group: 'C',
    fifaRanking: 8,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'Spain at FIFA World Cup 2026 — Fixtures, Results & Squad | GoalRadar',
    metaDesc: 'Spain World Cup 2026 fixtures, results, group standing and squad. Follow La Roja — schedule, TV guide and match updates.',
    intro: 'Spain, three-time world champions, enter the FIFA World Cup 2026 on the back of a rejuvenated era under their youthful squad. La Roja\'s dominant passing style and technical quality make them consistent dark-horse challengers to the title.',
  },
  {
    slug: 'germany',
    displayName: 'Germany',
    shortName: 'Germany',
    apiName: 'Germany',
    flag: '🇩🇪',
    group: 'D',
    fifaRanking: 12,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'Germany at FIFA World Cup 2026 — Fixtures, Results & Squad | GoalRadar',
    metaDesc: 'Germany World Cup 2026 fixtures, results, group standing and squad. Follow Die Mannschaft — schedule, TV guide and match updates.',
    intro: 'Germany, four-time world champions, enter the FIFA World Cup 2026 with renewed optimism after rebuilding following their 2022 group-stage exit. Die Mannschaft boast world-class talent and the tactical depth to be genuine title contenders once more.',
  },
  {
    slug: 'portugal',
    displayName: 'Portugal',
    shortName: 'Portugal',
    apiName: 'Portugal',
    flag: '🇵🇹',
    group: 'E',
    fifaRanking: 6,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'Portugal at FIFA World Cup 2026 — Fixtures, Results & Squad | GoalRadar',
    metaDesc: 'Portugal World Cup 2026 fixtures, results, group standing and squad. Follow A Seleção das Quinas — schedule, TV guide and match updates.',
    intro: 'Portugal enter the FIFA World Cup 2026 in a new era, with a talented generation looking to fulfil their tournament potential. A Seleção das Quinas have consistently reached the knockout rounds and in 2026 they will look to go all the way.',
  },
  {
    slug: 'netherlands',
    displayName: 'Netherlands',
    shortName: 'Netherlands',
    apiName: 'Netherlands',
    flag: '🇳🇱',
    group: 'F',
    fifaRanking: 7,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'Netherlands at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Netherlands World Cup 2026 fixtures, results and group standing. Oranje World Cup schedule and match updates.',
    intro: 'The Netherlands, three-time runners-up in the World Cup, bring a strong and cohesive squad to the 2026 tournament. Oranje are blessed with technical quality throughout their squad and have been among Europe\'s most consistent sides in recent qualifying campaigns.',
  },
  {
    slug: 'italy',
    displayName: 'Italy',
    shortName: 'Italy',
    apiName: 'Italy',
    flag: '🇮🇹',
    group: 'TBD',
    fifaRanking: 10,
    confederation: 'UEFA',
    qualified: false,
    metaTitle: 'Italy & FIFA World Cup 2026 | GoalRadar',
    metaDesc: 'Italy did not qualify for the FIFA World Cup 2026. Gli Azzurri were eliminated in UEFA qualifying.',
    intro: 'Italy, four-time world champions, did not qualify for the FIFA World Cup 2026, failing to advance through the UEFA qualifying process.',
  },
  {
    slug: 'belgium',
    displayName: 'Belgium',
    shortName: 'Belgium',
    apiName: 'Belgium',
    flag: '🇧🇪',
    group: 'H',
    fifaRanking: 3,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'Belgium at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Belgium World Cup 2026 fixtures, results and group standing. Red Devils World Cup schedule and match updates.',
    intro: 'Belgium arrive at the FIFA World Cup 2026 with a renewed generation following the "golden generation" era. The Red Devils remain highly competitive and have the quality to challenge for the knockout rounds.',
  },
  {
    slug: 'poland',
    displayName: 'Poland',
    shortName: 'Poland',
    apiName: 'Poland',
    flag: '🇵🇱',
    group: 'I',
    fifaRanking: 26,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'Poland at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Poland World Cup 2026 fixtures, results and group standing. Biało-czerwoni World Cup schedule and match updates.',
    intro: 'Poland qualified for the FIFA World Cup 2026 and enter the tournament led by their talismanic striker. The Polish side are disciplined and organized, capable of causing upsets when at their best.',
  },
  {
    slug: 'croatia',
    displayName: 'Croatia',
    shortName: 'Croatia',
    apiName: 'Croatia',
    flag: '🇭🇷',
    group: 'J',
    fifaRanking: 11,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'Croatia at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Croatia World Cup 2026 fixtures, results and group standing. Vatreni World Cup schedule and match updates.',
    intro: 'Croatia, runners-up in 2018, continue to punch above their weight at the World Cup. The Vatreni have an outstanding record in the tournament and their midfield quality and team cohesion make them perennial knockout-stage contenders.',
  },
  {
    slug: 'turkey',
    displayName: 'Türkiye',
    shortName: 'Türkiye',
    apiName: 'Türkiye',
    flag: '🇹🇷',
    group: 'K',
    fifaRanking: 22,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'Türkiye at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Türkiye World Cup 2026 fixtures, results and group standing. World Cup schedule and match updates.',
    intro: 'Türkiye qualified for the FIFA World Cup 2026 after a strong European campaign. With a blend of Premier League stars and domestic talent, the Turkish side are capable of a deep run in the tournament.',
  },
  {
    slug: 'austria',
    displayName: 'Austria',
    shortName: 'Austria',
    apiName: 'Austria',
    flag: '🇦🇹',
    group: 'L',
    fifaRanking: 25,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'Austria at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Austria World Cup 2026 fixtures, results and group standing. Das Team World Cup schedule and match updates.',
    intro: 'Austria qualified for the FIFA World Cup 2026 — their first tournament since 1998. Das Team have been one of Europe\'s most improved sides and bring an exciting, technically proficient squad to North America.',
  },
  {
    slug: 'switzerland',
    displayName: 'Switzerland',
    shortName: 'Switzerland',
    apiName: 'Switzerland',
    flag: '🇨🇭',
    group: 'A',
    fifaRanking: 19,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'Switzerland at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Switzerland World Cup 2026 fixtures, results and group standing. La Nati World Cup schedule and match updates.',
    intro: 'Switzerland have established themselves as one of Europe\'s most reliable tournament sides. La Nati have consistently qualified for and progressed at major tournaments, and the 2026 World Cup represents another opportunity to reach the latter stages.',
  },
  {
    slug: 'denmark',
    displayName: 'Denmark',
    shortName: 'Denmark',
    apiName: 'Denmark',
    flag: '🇩🇰',
    group: 'B',
    fifaRanking: 23,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'Denmark at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Denmark World Cup 2026 fixtures, results and group standing. Danish Dynamite World Cup schedule and match updates.',
    intro: 'Denmark arrive at the FIFA World Cup 2026 as one of Europe\'s most cohesive sides. Known for their pressing, hard work and collective spirit, the Danes are always capable of beating stronger opponents on their day.',
  },
  {
    slug: 'serbia',
    displayName: 'Serbia',
    shortName: 'Serbia',
    apiName: 'Serbia',
    flag: '🇷🇸',
    group: 'C',
    fifaRanking: 33,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'Serbia at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Serbia World Cup 2026 fixtures, results and group standing. Orlovi World Cup schedule and match updates.',
    intro: 'Serbia qualified for the FIFA World Cup 2026 after a competitive European qualification campaign. The Orlovi are a physically imposing side with world-class talent in attack and are capable of causing upsets at the tournament.',
  },
  // ── CAF (9) ───────────────────────────────────────────────────────────────
  {
    slug: 'morocco',
    displayName: 'Morocco',
    shortName: 'Morocco',
    apiName: 'Morocco',
    flag: '🇲🇦',
    group: 'D',
    fifaRanking: 14,
    confederation: 'CAF',
    qualified: true,
    metaTitle: 'Morocco at FIFA World Cup 2026 — Fixtures, Results & Squad | GoalRadar',
    metaDesc: 'Morocco World Cup 2026 fixtures, results and group standing. Atlas Lions World Cup schedule and match updates.',
    intro: 'Morocco, semi-finalists at the 2022 World Cup, arrive in 2026 as one of the most exciting sides on the planet. The Atlas Lions are hungry to go one better and have the talent and collective spirit to challenge the very best.',
  },
  {
    slug: 'senegal',
    displayName: 'Senegal',
    shortName: 'Senegal',
    apiName: 'Senegal',
    flag: '🇸🇳',
    group: 'E',
    fifaRanking: 20,
    confederation: 'CAF',
    qualified: true,
    metaTitle: 'Senegal at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Senegal World Cup 2026 fixtures, results and group standing. Lions of Teranga World Cup schedule and match updates.',
    intro: 'Senegal, AFCON champions and 2002 World Cup semi-finalists, are one of Africa\'s strongest representatives at the 2026 World Cup. The Lions of Teranga bring pace, power and world-class talent throughout their squad.',
  },
  {
    slug: 'nigeria',
    displayName: 'Nigeria',
    shortName: 'Nigeria',
    apiName: 'Nigeria',
    flag: '🇳🇬',
    group: 'F',
    fifaRanking: 40,
    confederation: 'CAF',
    qualified: true,
    metaTitle: 'Nigeria at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Nigeria World Cup 2026 fixtures, results and group standing. Super Eagles World Cup schedule and match updates.',
    intro: 'Nigeria\'s Super Eagles are one of Africa\'s most historically successful World Cup sides. With a new generation of talent emerging in European leagues, the 2026 World Cup represents an opportunity for Nigeria to re-establish themselves on the global stage.',
  },
  {
    slug: 'egypt',
    displayName: 'Egypt',
    shortName: 'Egypt',
    apiName: 'Egypt',
    flag: '🇪🇬',
    group: 'G',
    fifaRanking: 34,
    confederation: 'CAF',
    qualified: true,
    metaTitle: 'Egypt at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Egypt World Cup 2026 fixtures, results and group standing. Pharaohs World Cup schedule and match updates.',
    intro: 'Egypt qualified for the FIFA World Cup 2026 after a strong CAF qualification campaign. The Pharaohs, led by their talismanic captain, will look to make history and advance from the group stage for the first time since 1990.',
  },
  {
    slug: 'cameroon',
    displayName: 'Cameroon',
    shortName: 'Cameroon',
    apiName: 'Cameroon',
    flag: '🇨🇲',
    group: 'H',
    fifaRanking: 41,
    confederation: 'CAF',
    qualified: true,
    metaTitle: 'Cameroon at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Cameroon World Cup 2026 fixtures, results and group standing. Indomitable Lions World Cup schedule and match updates.',
    intro: 'Cameroon, the Indomitable Lions, are one of Africa\'s most storied World Cup nations, having reached the quarter-finals in 1990. In 2026 they bring a new generation hungry to emulate those iconic performances.',
  },
  {
    slug: 'ivory-coast',
    displayName: 'Ivory Coast',
    shortName: 'Ivory Coast',
    apiName: "Côte d'Ivoire",
    flag: '🇨🇮',
    group: 'I',
    fifaRanking: 29,
    confederation: 'CAF',
    qualified: true,
    metaTitle: 'Ivory Coast at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Ivory Coast World Cup 2026 fixtures, results and group standing. Les Éléphants World Cup schedule and match updates.',
    intro: 'Ivory Coast, AFCON 2023 champions on home soil, carry enormous momentum into the FIFA World Cup 2026. Les Éléphants have world-class talent from European leagues and are among the strongest African sides in North America.',
  },
  {
    slug: 'south-africa',
    displayName: 'South Africa',
    shortName: 'South Africa',
    apiName: 'South Africa',
    flag: '🇿🇦',
    group: 'J',
    fifaRanking: 60,
    confederation: 'CAF',
    qualified: true,
    metaTitle: 'South Africa at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'South Africa World Cup 2026 fixtures, results and group standing. Bafana Bafana World Cup schedule and match updates.',
    intro: 'South Africa face Mexico in the opening match of the FIFA World Cup 2026 at Azteca Stadium — a dramatic return to the World Cup stage for Bafana Bafana. The Mexicans hosted them at the 2010 World Cup, and the fixture carries enormous symbolic weight.',
  },
  {
    slug: 'ghana',
    displayName: 'Ghana',
    shortName: 'Ghana',
    apiName: 'Ghana',
    flag: '🇬🇭',
    group: 'K',
    fifaRanking: 55,
    confederation: 'CAF',
    qualified: true,
    metaTitle: 'Ghana at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Ghana World Cup 2026 fixtures, results and group standing. Black Stars World Cup schedule and match updates.',
    intro: 'Ghana\'s Black Stars have a proud World Cup history, including a memorable quarter-final run in 2010. The 2026 tournament offers them another opportunity to advance deep into the knockout stages with a talented squad.',
  },
  {
    slug: 'algeria',
    displayName: 'Algeria',
    shortName: 'Algeria',
    apiName: 'Algeria',
    flag: '🇩🇿',
    group: 'L',
    fifaRanking: 36,
    confederation: 'CAF',
    qualified: true,
    metaTitle: 'Algeria at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Algeria World Cup 2026 fixtures, results and group standing. Les Fennecs World Cup schedule and match updates.',
    intro: 'Algeria qualified for the FIFA World Cup 2026 and bring a talented squad to North America. Les Fennecs have been AFCON champions and are well-represented in European leagues, giving them the quality to compete at the highest level.',
  },
  // ── AFC (8) ───────────────────────────────────────────────────────────────
  {
    slug: 'japan',
    displayName: 'Japan',
    shortName: 'Japan',
    apiName: 'Japan',
    flag: '🇯🇵',
    group: 'A',
    fifaRanking: 17,
    confederation: 'AFC',
    qualified: true,
    metaTitle: 'Japan at FIFA World Cup 2026 — Fixtures, Results & Squad | GoalRadar',
    metaDesc: 'Japan World Cup 2026 fixtures, results and group standing. Samurai Blue World Cup schedule and match updates.',
    intro: 'Japan arrive at the FIFA World Cup 2026 as one of Asia\'s strongest sides and genuine knockout-stage contenders. The Samurai Blue have a new generation of European-based talent and shocked Germany and Spain at Qatar 2022 to finish top of their group.',
  },
  {
    slug: 'south-korea',
    displayName: 'South Korea',
    shortName: 'South Korea',
    apiName: 'Korea Republic',
    flag: '🇰🇷',
    group: 'B',
    fifaRanking: 24,
    confederation: 'AFC',
    qualified: true,
    metaTitle: 'South Korea at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'South Korea World Cup 2026 fixtures, results and group standing. Taeguk Warriors World Cup schedule and match updates.',
    intro: 'South Korea are one of Asia\'s most consistent World Cup sides, qualifying for eleven consecutive tournaments. The Taeguk Warriors bring Premier League-proven talent and an intense, high-energy playing style to the 2026 World Cup.',
  },
  {
    slug: 'australia',
    displayName: 'Australia',
    shortName: 'Australia',
    apiName: 'Australia',
    flag: '🇦🇺',
    group: 'C',
    fifaRanking: 25,
    confederation: 'AFC',
    qualified: true,
    metaTitle: 'Australia at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Australia World Cup 2026 fixtures, results and group standing. Socceroos World Cup schedule and match updates.',
    intro: 'Australia\'s Socceroos arrive at the FIFA World Cup 2026 after their memorable quarter-final run at Qatar 2022. With a core of experienced European-based players, the Socceroos will look to repeat or surpass that achievement.',
  },
  {
    slug: 'iran',
    displayName: 'Iran',
    shortName: 'Iran',
    apiName: 'Iran',
    flag: '🇮🇷',
    group: 'D',
    fifaRanking: 22,
    confederation: 'AFC',
    qualified: true,
    metaTitle: 'Iran at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Iran World Cup 2026 fixtures, results and group standing. Team Melli World Cup schedule and match updates.',
    intro: 'Iran qualified for the FIFA World Cup 2026, continuing their record as one of Asia\'s most consistent qualifiers. Team Melli are well-drilled and tactically disciplined under their coaching staff.',
  },
  {
    slug: 'saudi-arabia',
    displayName: 'Saudi Arabia',
    shortName: 'Saudi Arabia',
    apiName: 'Saudi Arabia',
    flag: '🇸🇦',
    group: 'E',
    fifaRanking: 56,
    confederation: 'AFC',
    qualified: true,
    metaTitle: 'Saudi Arabia at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Saudi Arabia World Cup 2026 fixtures, results and group standing. Al-Akhdar World Cup schedule and match updates.',
    intro: 'Saudi Arabia, who stunned Argentina 2–1 at Qatar 2022 in one of the greatest World Cup upsets, return in 2026. Al-Akhdar have invested heavily in their domestic league and hope to produce another memorable upset on the world stage.',
  },
  {
    slug: 'qatar',
    displayName: 'Qatar',
    shortName: 'Qatar',
    apiName: 'Qatar',
    flag: '🇶🇦',
    group: 'F',
    fifaRanking: 37,
    confederation: 'AFC',
    qualified: true,
    metaTitle: 'Qatar at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Qatar World Cup 2026 fixtures, results and group standing. Al Annabi World Cup schedule and match updates.',
    intro: 'Qatar return to the World Cup for the second time, having hosted the 2022 tournament. Al Annabi qualified through the AFC process and will be looking to improve on their 2022 group-stage exit on foreign soil.',
  },
  {
    slug: 'iraq',
    displayName: 'Iraq',
    shortName: 'Iraq',
    apiName: 'Iraq',
    flag: '🇮🇶',
    group: 'G',
    fifaRanking: 63,
    confederation: 'AFC',
    qualified: true,
    metaTitle: 'Iraq at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Iraq World Cup 2026 fixtures, results and group standing. Lions of Mesopotamia World Cup schedule and match updates.',
    intro: 'Iraq return to the FIFA World Cup for the first time since 1986, qualifying through a strong AFC campaign. The Lions of Mesopotamia bring a passionate squad to North America, with most players competing in the Middle East and wider Asian leagues.',
  },
  {
    slug: 'jordan',
    displayName: 'Jordan',
    shortName: 'Jordan',
    apiName: 'Jordan',
    flag: '🇯🇴',
    group: 'H',
    fifaRanking: 69,
    confederation: 'AFC',
    qualified: true,
    metaTitle: 'Jordan at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Jordan World Cup 2026 fixtures, results and group standing. Al-Nashama World Cup schedule and match updates.',
    intro: 'Jordan make their debut at the FIFA World Cup 2026 after a historic AFC qualification. Al-Nashama\'s journey to the World Cup is one of football\'s great underdog stories, and they arrive ready to make a mark.',
  },
  // ── OFC (1) ───────────────────────────────────────────────────────────────
  {
    slug: 'new-zealand',
    displayName: 'New Zealand',
    shortName: 'New Zealand',
    apiName: 'New Zealand',
    flag: '🇳🇿',
    group: 'I',
    fifaRanking: 91,
    confederation: 'OFC',
    qualified: true,
    metaTitle: 'New Zealand at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'New Zealand World Cup 2026 fixtures, results and group standing. All Whites World Cup schedule and match updates.',
    intro: 'New Zealand\'s All Whites qualified for the FIFA World Cup 2026 through the OFC pathway. The New Zealanders, whose success has been built around A-League and European-based players, are determined to make the most of their chance on the global stage.',
  },
  // ── Interconfederal / Playoff (2) ─── + missing Group L slot ─────────────
  {
    slug: 'bolivia',
    displayName: 'Bolivia',
    shortName: 'Bolivia',
    apiName: 'Bolivia',
    flag: '🇧🇴',
    group: 'L',
    fifaRanking: 79,
    confederation: 'CONMEBOL',
    qualified: true,
    metaTitle: 'Bolivia at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Bolivia World Cup 2026 fixtures, results and group standing. La Verde World Cup schedule and match updates.',
    intro: 'Bolivia qualified for the FIFA World Cup 2026 via the inter-confederation playoff, ending a long wait to return to the global stage. La Verde, playing from one of the world\'s highest capital cities in La Paz, bring physical resilience and determination to North America.',
  },
  // ── Interconfederal / Playoff ────────────────────────────────────────────
  {
    slug: 'peru',
    displayName: 'Peru',
    shortName: 'Peru',
    apiName: 'Peru',
    flag: '🇵🇪',
    group: 'J',
    fifaRanking: 72,
    confederation: 'CONMEBOL',
    qualified: true,
    metaTitle: 'Peru at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Peru World Cup 2026 fixtures, results and group standing. La Bicolor World Cup schedule and match updates.',
    intro: 'Peru return to the World Cup stage at the 2026 tournament. La Blanquirroja bring a passionate South American style and experienced squad, determined to advance beyond the group stage.',
  },
  {
    slug: 'ukraine',
    displayName: 'Ukraine',
    shortName: 'Ukraine',
    apiName: 'Ukraine',
    flag: '🇺🇦',
    group: 'K',
    fifaRanking: 21,
    confederation: 'UEFA',
    qualified: true,
    metaTitle: 'Ukraine at FIFA World Cup 2026 — Fixtures & Results | GoalRadar',
    metaDesc: 'Ukraine World Cup 2026 fixtures, results and group standing. Zbirna World Cup schedule and match updates.',
    intro: 'Ukraine qualified for the FIFA World Cup 2026 under extraordinary circumstances. Zbirna carry the hopes of their nation to North America, with Premier League and European-based players forming a competitive squad.',
  },
];

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export const WC_ALL_TEAM_SLUGS = WC_ALL_TEAMS.map((t) => t.slug);

export function getWCTeam(slug: string): WCTeamEntry | undefined {
  return WC_ALL_TEAMS.find((t) => t.slug === slug);
}

/** Lookup by API name (used to match football-data.org team names) */
export function getWCTeamByApiName(apiName: string): WCTeamEntry | undefined {
  return WC_ALL_TEAMS.find(
    (t) => t.apiName.toLowerCase() === apiName.toLowerCase()
  );
}
