/**
 * StoryCardStrip — DATA-18WC.EXPERIENCE.V2
 *
 * Renders an array of StoryCard objects as a horizontal scrollable strip.
 * Cards are purely display — generated by buildStoryCards() in match-story-engine.ts.
 *
 * Reuses: StoryCard type from match-story-engine.ts
 * Does NOT fetch. Does NOT call any engine. Receives cards as props.
 */

import type { StoryCard, StoryCardType } from '@/lib/match-story-engine';

// ---------------------------------------------------------------------------
// Card colour map — type → Tailwind classes
// ---------------------------------------------------------------------------

const CARD_STYLES: Record<StoryCardType, { border: string; bg: string; icon: string }> = {
  WINNER_ADVANCES:    { border: 'border-green-500/40',  bg: 'bg-green-950/30',  icon: '🏆' },
  LOSER_ELIMINATED:  { border: 'border-red-500/40',    bg: 'bg-red-950/20',    icon: '💔' },
  QUALIFIED:         { border: 'border-green-500/40',  bg: 'bg-green-950/30',  icon: '✅' },
  MUST_WIN:          { border: 'border-orange-500/40', bg: 'bg-orange-950/20', icon: '⚡' },
  CAN_STILL_QUALIFY: { border: 'border-yellow-500/40', bg: 'bg-yellow-950/20', icon: '🌟' },
  HOST_NATION:       { border: 'border-amber-500/40',  bg: 'bg-amber-950/20',  icon: '🏠' },
  FIRST_WC_MEETING:  { border: 'border-blue-500/40',   bg: 'bg-blue-950/20',   icon: '🤝' },
  FINAL_COUNTDOWN:   { border: 'border-yellow-400/60', bg: 'bg-yellow-950/30', icon: '🌍' },
  PENALTY_DRAMA:     { border: 'border-purple-500/40', bg: 'bg-purple-950/20', icon: '🥅' },
  EXTRA_TIME:        { border: 'border-blue-400/40',   bg: 'bg-blue-950/20',   icon: '⏱️' },
};

// ---------------------------------------------------------------------------
// Single card
// ---------------------------------------------------------------------------

function Card({ card }: { card: StoryCard }) {
  const style = CARD_STYLES[card.type] ?? CARD_STYLES.MUST_WIN;
  return (
    <div
      className={`
        flex-shrink-0 w-44 sm:w-52 rounded-xl border p-3.5
        ${style.border} ${style.bg}
        flex flex-col gap-1.5
      `}
    >
      <div className="flex items-center gap-1.5">
        <span className="text-base leading-none" aria-hidden="true">{card.icon}</span>
        <span className="text-xs font-bold text-white leading-tight">{card.headline}</span>
      </div>
      <p className="text-xs text-gray-400 leading-snug">{card.body}</p>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Strip
// ---------------------------------------------------------------------------

export default function StoryCardStrip({
  cards,
  className = '',
}: {
  cards: StoryCard[];
  className?: string;
}) {
  if (!cards.length) return null;

  return (
    <div
      className={`flex gap-3 overflow-x-auto pb-1 scrollbar-none ${className}`}
      role="list"
      aria-label="Match storylines"
    >
      {cards.map((card, i) => (
        <div key={i} role="listitem">
          <Card card={card} />
        </div>
      ))}
    </div>
  );
}
