/**
 * Sitemap index handler — reachable at /sitemap.xml via a rewrite in next.config.ts.
 *
 * Why this exists instead of src/app/sitemap.xml/route.ts:
 *   When sitemap.ts exports generateSitemaps(), Next.js internally registers
 *   the metadata file at the /sitemap.xml/route filesystem path. Any custom
 *   route.ts at that same path produces a Turbopack "conflicting route and
 *   metadata" build error. The fix is to serve the index from an /api/ path
 *   and rewrite /sitemap.xml → /api/sitemap-index at the Next.js edge.
 *
 * Child sitemaps (generated by generateSitemaps() in src/app/sitemap.ts):
 *   /sitemap/0.xml  — core & static pages
 *   /sitemap/1.xml  — WC 2026 flat-URL SEO pages
 *   /sitemap/2.xml  — WC 2026 hub pages
 *   /sitemap/3.xml  — competition & league pages
 *   /sitemap/4.xml  — match pages (recent + upcoming, dynamic)
 *   /sitemap/5.xml  — team pages (built from standings)
 *
 * Cache: CDN caches for 1 hour (matches sitemap.ts revalidate = 3600).
 */

const BASE_URL = 'https://goalradar.org';

// Keep in sync with the ids returned by generateSitemaps() in src/app/sitemap.ts
const SITEMAP_IDS = [0, 1, 2, 3, 4, 5];

export const dynamic = 'force-static';

export async function GET() {
  const entries = SITEMAP_IDS.map(
    (id) =>
      `  <sitemap>\n    <loc>${BASE_URL}/sitemap/${id}.xml</loc>\n  </sitemap>`,
  ).join('\n');

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    entries,
    '</sitemapindex>',
  ].join('\n');

  return new Response(xml, {
    status: 200,
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 's-maxage=3600, stale-while-revalidate=86400',
    },
  });
}
